CREATE TABLE IF NOT EXISTS account(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	number INT(20) NOT NULL UNIQUE,
	balance DECIMAL(15,2) NOT NULL,
	email VARCHAR(50) NOT NULL
	
) ENGINE = InnoDB DEFAULT CHARSET = utf8;